//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleProject.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ValidationSoap")]
    public interface ValidationSoap {
        
        // CODEGEN: Generating message contract since element name cn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insurance", ReplyAction="*")]
        VehicleProject.ServiceReference1.InsuranceResponse Insurance(VehicleProject.ServiceReference1.InsuranceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insurance", ReplyAction="*")]
        System.Threading.Tasks.Task<VehicleProject.ServiceReference1.InsuranceResponse> InsuranceAsync(VehicleProject.ServiceReference1.InsuranceRequest request);
        
        // CODEGEN: Generating message contract since element name ln from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fitness", ReplyAction="*")]
        VehicleProject.ServiceReference1.FitnessResponse Fitness(VehicleProject.ServiceReference1.FitnessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fitness", ReplyAction="*")]
        System.Threading.Tasks.Task<VehicleProject.ServiceReference1.FitnessResponse> FitnessAsync(VehicleProject.ServiceReference1.FitnessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsuranceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insurance", Namespace="http://tempuri.org/", Order=0)]
        public VehicleProject.ServiceReference1.InsuranceRequestBody Body;
        
        public InsuranceRequest() {
        }
        
        public InsuranceRequest(VehicleProject.ServiceReference1.InsuranceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsuranceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cn;
        
        public InsuranceRequestBody() {
        }
        
        public InsuranceRequestBody(string cn) {
            this.cn = cn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsuranceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsuranceResponse", Namespace="http://tempuri.org/", Order=0)]
        public VehicleProject.ServiceReference1.InsuranceResponseBody Body;
        
        public InsuranceResponse() {
        }
        
        public InsuranceResponse(VehicleProject.ServiceReference1.InsuranceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsuranceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VehicleProject.ServiceReference1.ArrayOfAnyType InsuranceResult;
        
        public InsuranceResponseBody() {
        }
        
        public InsuranceResponseBody(VehicleProject.ServiceReference1.ArrayOfAnyType InsuranceResult) {
            this.InsuranceResult = InsuranceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FitnessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fitness", Namespace="http://tempuri.org/", Order=0)]
        public VehicleProject.ServiceReference1.FitnessRequestBody Body;
        
        public FitnessRequest() {
        }
        
        public FitnessRequest(VehicleProject.ServiceReference1.FitnessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FitnessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ln;
        
        public FitnessRequestBody() {
        }
        
        public FitnessRequestBody(string ln) {
            this.ln = ln;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FitnessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FitnessResponse", Namespace="http://tempuri.org/", Order=0)]
        public VehicleProject.ServiceReference1.FitnessResponseBody Body;
        
        public FitnessResponse() {
        }
        
        public FitnessResponse(VehicleProject.ServiceReference1.FitnessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FitnessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VehicleProject.ServiceReference1.ArrayOfAnyType FitnessResult;
        
        public FitnessResponseBody() {
        }
        
        public FitnessResponseBody(VehicleProject.ServiceReference1.ArrayOfAnyType FitnessResult) {
            this.FitnessResult = FitnessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidationSoapChannel : VehicleProject.ServiceReference1.ValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationSoapClient : System.ServiceModel.ClientBase<VehicleProject.ServiceReference1.ValidationSoap>, VehicleProject.ServiceReference1.ValidationSoap {
        
        public ValidationSoapClient() {
        }
        
        public ValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VehicleProject.ServiceReference1.InsuranceResponse VehicleProject.ServiceReference1.ValidationSoap.Insurance(VehicleProject.ServiceReference1.InsuranceRequest request) {
            return base.Channel.Insurance(request);
        }
        
        public VehicleProject.ServiceReference1.ArrayOfAnyType Insurance(string cn) {
            VehicleProject.ServiceReference1.InsuranceRequest inValue = new VehicleProject.ServiceReference1.InsuranceRequest();
            inValue.Body = new VehicleProject.ServiceReference1.InsuranceRequestBody();
            inValue.Body.cn = cn;
            VehicleProject.ServiceReference1.InsuranceResponse retVal = ((VehicleProject.ServiceReference1.ValidationSoap)(this)).Insurance(inValue);
            return retVal.Body.InsuranceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VehicleProject.ServiceReference1.InsuranceResponse> VehicleProject.ServiceReference1.ValidationSoap.InsuranceAsync(VehicleProject.ServiceReference1.InsuranceRequest request) {
            return base.Channel.InsuranceAsync(request);
        }
        
        public System.Threading.Tasks.Task<VehicleProject.ServiceReference1.InsuranceResponse> InsuranceAsync(string cn) {
            VehicleProject.ServiceReference1.InsuranceRequest inValue = new VehicleProject.ServiceReference1.InsuranceRequest();
            inValue.Body = new VehicleProject.ServiceReference1.InsuranceRequestBody();
            inValue.Body.cn = cn;
            return ((VehicleProject.ServiceReference1.ValidationSoap)(this)).InsuranceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VehicleProject.ServiceReference1.FitnessResponse VehicleProject.ServiceReference1.ValidationSoap.Fitness(VehicleProject.ServiceReference1.FitnessRequest request) {
            return base.Channel.Fitness(request);
        }
        
        public VehicleProject.ServiceReference1.ArrayOfAnyType Fitness(string ln) {
            VehicleProject.ServiceReference1.FitnessRequest inValue = new VehicleProject.ServiceReference1.FitnessRequest();
            inValue.Body = new VehicleProject.ServiceReference1.FitnessRequestBody();
            inValue.Body.ln = ln;
            VehicleProject.ServiceReference1.FitnessResponse retVal = ((VehicleProject.ServiceReference1.ValidationSoap)(this)).Fitness(inValue);
            return retVal.Body.FitnessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VehicleProject.ServiceReference1.FitnessResponse> VehicleProject.ServiceReference1.ValidationSoap.FitnessAsync(VehicleProject.ServiceReference1.FitnessRequest request) {
            return base.Channel.FitnessAsync(request);
        }
        
        public System.Threading.Tasks.Task<VehicleProject.ServiceReference1.FitnessResponse> FitnessAsync(string ln) {
            VehicleProject.ServiceReference1.FitnessRequest inValue = new VehicleProject.ServiceReference1.FitnessRequest();
            inValue.Body = new VehicleProject.ServiceReference1.FitnessRequestBody();
            inValue.Body.ln = ln;
            return ((VehicleProject.ServiceReference1.ValidationSoap)(this)).FitnessAsync(inValue);
        }
    }
}
